# Each page blueprint must have a title, the title may be different from the file name
# This default blueprint is used to display a page in the Panel whenever a custom page blueprint is missing.
title: Page

tabs:
  main:
    label: Main
    icon: text
    columns:
      main:
        width: 1/1
        fields:
          hero_image:
            label: Image
            type: files
            width: 1/2
            max: 1
            min: 1
            layout: cards
          main_content:
            label: Main Content
            type: textarea
            size: medium
            width: 1/2
  uploads:
    label: Uploads
    icon: file
    sections:
      file_uploads:
        headline: Uploads
        type: files
